production:
  adapter: 'makara_mysql2'
  database: 'voicealert'
  username: 'voicealert'
  password: 'voicealert'
  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: false
    rescue_connection_failures: true
    connections:
      - role: master
        host: 10.10.10.10
      - role: slave
        host: 10.10.10.11

# production:
#   adapter: seamless_database_pool
#   database: voicealert
#   username: voicealert
#   password: voicealert
#   pool_adapter: mysql2
#   port: 3306
#   master:
#     host: 10.10.10.10
#     port: 3306
#     username: voicealert
#     password: voicealert
#   read_pool:
#     - host: 10.10.10.10
#       pool_weight: 2
#     - host: 10.10.10.11